### ISSUE TITLE
Recruiting additional maintainers for Standard ML

### ISSUE THREAD

**Issue by kytrinyx** [exercism/sml#125]
We're about to start a big push towards version 3 (v3) of Exercism. This is going to be a really exciting step forward for Exercism, with in-browser coding, new Concept Exercises with automated feedback, improved mentoring and much more.

This to be a big community effort, with the work spread out among hundreds of volunteers across Exercism. One key thing is going to be each track having enough maintainers who have the time to manage that community effort. We are therefore putting out a call for new maintainers to bolster our numbers. We're hoping that our existing maintainers will be able to act as mentors to the newer maintainers we add, and take on a parental role in the tracks.

If you are an existing maintainer, could you please reply to this letting us know that you think you'll have time (2-3hrs/week) to help with this over the next 6 months. If you won't have that time, but still want to be a maintainer and just help where you can instead, please tell us that too. If you have come to the end of the road as a maintainer, then we totally understand that and appreciate all your effort, so just let us know.

For anyone new who's interested in becoming a maintainer, thanks for your interest! Being an Exercism maintainer is also a great opportunity to work with some other smart people, learn more about your language of choice, and gain useful skills and experience that are useful for growing your career in the technical leadership direction. Please write a comment below introducing yourself along with your Exercism handle, and telling us why you're interested in becoming a maintainer, and any relevant experience. We will then evaluate every application and contact you using your exercism email address once we have finished the evaluation process.

Thank you!

See also https://github.com/exercism/exercism/issues/5161

**Comment by k4rtik** [comment]
I would like to be a maintainer. I have worked on Exercism in the past and was a teaching assistant for a Programming Languages class taught at UChicago that uses SML for implementation. My handle is @k4rtik (same as GitHub).

**Comment by sshine** [comment]
That is very interesting to hear, @k4rtik!

I was a TA in various FP and compiler courses at uni of Copenhagen (DIKU), which is also where I know sml from.

I'm an existing (passive) maintainer. I was the last to have a spree of activity as mentor and maintainer on this track. The bulk of the track's exercises were made by others, some of which are still subscribed.

SML never reached "v2" state, so this would be a first effort to structure a curriculum. My idea one year ago with both of SML and OCaml tracks were to mirror the much more developed Haskell track's selection of "core" exercises, to minimize effort.

I eventually stopped pursuing this as so very, very few students follow the SML track at all. The OCaml track was quite active but eventually lost its active mentors a year ago.

If you think this mirroring strategy could be worthwhile, [my proposal in Haskell track](https://github.com/exercism/haskell/issues/887) is to build exercises around CIS 194's curriculum structure.

**Comment by k4rtik** [comment]
Hi @sshine, nice to meet you here!

The only thing I can say at this point is that it doesn't hurt to have similar exercises in different languages. It works for people learning how to solve exercises using programming and it also works for people trying to pick up another language without necessarily wanting to spend time on solving edge cases for the problems they have worked on before in a different language on exercism.

**Comment by sshine** [comment]
@k4rtik: By the way, feel free to submit a pull request that adds you to config/maintainers.json in this repository, since it triggers some automation wrt. access control.. You are free to choose between `"show_on_website": true` or `"show_on_website": false`. I doubt that you'll get any unwanted attention from this.

**Comment by rainij** [comment]
@ErikSchierboom if I am not mistaken there is currently no community maintainer for the sml-repo. Is that right?

In any case, I would like to become a maintainer, at least for the next six month. Besides adding a few new exercises I would also look into issues as I have already done before. Depending on the number of PRs I could also review some of them. I think *on average* I can spend 2h per week. For smaller things I can react in 24h I think. For larger things (like review of a large PR) I usually quickly give feedback with an information when I might have time for that.

Let me know what you think and whether I have to do something to become a maintainer.

**Comment by k4rtik** [comment]
> if I am not mistaken there is currently no community maintainer for the sml-repo. Is that right?

It's probably right. At least, I was not able to contribute while the transition to v3 was happening. And I will not have more time in the foreseeable future.

**Comment by ErikSchierboom** [comment]
@rainij You've done great work, so I think you'll fit well as a maintainer. @iHiD could you add @rainij to the `sml` team?

**Comment by iHiD** [comment]
Done. Thank you @rainij!
