### ISSUE TITLE
Travis CI: Bump Poly/ML from 5.7 to 5.8

### ISSUE THREAD

**Issue by sshine** [exercism/sml#128]
A new (March 2019) version of Poly/ML is available:

https://github.com/polyml/polyml/releases

An easy fix is to just update .travis.yml with this version bump.

A more laborious fix would be to somehow cache the compiled binary so that we don't build it every time Travis CI starts. Impressively, though, it still only runs for 49 seconds at this point in time, so perhaps it isn't really critical at all. https://travis-ci.org/exercism/sml/builds/656188797#L185

**Comment by sshine** [comment]
@k4rtik: If you're looking for a first contribution, here is a low-hanging fruit!

**Comment by k4rtik** [comment]
Sure, please assign it to me.

**Comment by sshine** [comment]
Feel free to choose your preferred scope and submit a pull request.
