### ISSUE TITLE
Check docs are up to date

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/sml#182]
Please check if your documentation files are still up-to-date.

The key documentation files to check are:

- `docs/ABOUT.md`
- `docs/INSTALLATION.md`
- `docs/LEARNING.md`
- `docs/RESOURCES.md`
- `docs/TESTS.md`
- `exercises/shared/.docs/help.md`
- `exercises/shared/.docs/tests.md`

There might be more.

## Link check report

To help identify invalid links, we've automatically checked the links of _all_ `*.md` files in this repo.
This is the report of that check:

<pre style="color:#bbb;white-space:pre-wrap;word-wrap:break-word;overflow-wrap:break-word">📝 Summary
---------------------
🔍 Total...........63
✅ Successful......61
⏳ Timeouts.........1
🔀 Redirected.......0
👻 Excluded.........0
🚫 Errors...........1

Errors in ./docs/RESOURCES.md
<span style="color:#ff5555">✗ http://www.elsman.com/mlkit/ (error sending request for url (http://www.elsman.com/mlkit/): error trying to connect: dns error: failed to lookup address information: Name or service not known)</span>

Errors in ./docs/LEARNING.md
<span style="color:#ffff55">⧖ http://www.soc.napier.ac.uk/course-notes/sml/manual.html</span>

</pre>
## Tracking

https://github.com/exercism/v3-launch/issues/54

**Comment by kahgoh** [comment]
@ErikSchierboom The URL http://www.elsman.com/mlkit/ seems to work now. #309 updates the other link.
