### ISSUE TITLE
Planets are out of order in the datatype declaration for space-age

### ISSUE THREAD

**Issue by dapritchard** [exercism/sml#214]
`two-fer.sml` has the following datatype declaration.
```sml
datatype planet = Mercury | Venus | Earth | Mars
                | Jupiter | Saturn | Neptune | Uranus
```
However, the `Neptune` and `Uranus` variants are out of order in terms of the ordering of the planets in distance from the sun, as well as the ordering in the corresponding `instructions.md` from top to bottom of the page.

I was carelessly copy/pasting lines of code based on the order of planets in the datatype declaration and ended up with having the 'number of earth years' coefficients swapped for Neptune and Uranus which caused me a few minutes of confusion. I'm mentioning this here in the hopes of potentially saving the next person from the same mistake.

Many thanks for providing this fantastic resource!

**Comment by rainij** [comment]
@dapritchard thanks for reporting this. I will take care of this.
