### ISSUE TITLE
Exercises on website not in sync with repo

### ISSUE THREAD

**Issue by rainij** [exercism/sml#231]
Usually when an exercise is updated and the corresponding PR is merged the website reflects this change after a few minutes. At least this is what I observed in the past.

Two days ago PR https://github.com/exercism/sml/pull/229 on `sum-of-multiples` was merged. I observed that the change did not reach the website (compare the instructions), at least not completely. Something reached the website since I approved the PR and this shows up in my contributions on the website. But not the instructions. I waited two days but still no change.

So I have the suspicion that _something_ is broken. I did not see any obvious reason in the sml repo or the actions. Maybe the website build process has changed and assumes these files to be somewhere else? I don't know.

**Comment by kytrinyx** [comment]
It sounds like there's a problem. I'm wondering if it is a temporary glitch. Would you merge this and see if it is enough to get everything back up to date? https://github.com/exercism/sml/pull/232

**Comment by kytrinyx** [comment]
No, it should be quick.

**Comment by kytrinyx** [comment]
Ok, Erik did a forced sync, and now we need to check if that is enough to get this working again.

Here's a new PR that syncs exercise descriptions from problem-specifications:
https://github.com/exercism/sml/pull/233

Would you merge that and see if the sync to the website kicks off?

**Comment by rainij** [comment]
I merged https://github.com/exercism/sml/pull/233 but still no luck. I compared this https://exercism.org/tracks/sml/exercises/sum-of-multiples with the repo and besides the text being old it says `Last updated 14 March 2023` (which is consistent with the text as far as I can see).

**Comment by kytrinyx** [comment]
Ok! This is something we will need to dig into next week.

**Comment by ErikSchierboom** [comment]
But https://github.com/exercism/sml/pull/233/files doesn't change sum-of-multiples

**Comment by kytrinyx** [comment]
It changes accumulate, but https://exercism.org/tracks/sml/exercises/accumulate says that it was last updated 15 March 2023

**Comment by rainij** [comment]
It seems to work now. A recently merged PR (https://github.com/exercism/sml/pull/245) propagated correctly to the website.
