### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by iHiD** [exercism/sml#316]
@rainij You have qualified to be a maintainer here. Thank you for your hard work! Would you like to join?

**Comment by rainij** [comment]
Hi @iHiD. Unfortunately in  the foreseeable future I won't be able to work much on the project. I might come back to exercism as a contributor in the future. Maybe on another track.

Btw.: Thanks to to exercism team for this nice website.

**Comment by iHiD** [comment]
No problem. Thanks for letting me know and your work so far :)
