### ISSUE TITLE
Identify core exercises

### ISSUE THREAD

**Issue by snahor** [exercism/sml#72]
o far we have 3 core exercises: 

- `hello-world`
- `two-fer`
- `leap`

 and we need at least 8 (IIRC).

Candidates from the existing ones:
- `bob`
- `atbash-cipher`
- `allergies`
- `accumulate`
- `flatten-array`
- `difference-of-squares`
- `hamming`
- `prime-factors`
- `allergies`
- `pangram`
- `raindrops`
- `sum-of-multiples`

I checked other repos (fsharp, java and ecmascript) and collected these:
- `bank-account`
- `beer-song`
- `binary`
- `binary-search`
- `clock`
- `gigasecond`
- `grade-school`
- `kindergarten-garden`
- `linked-list`
- `list-ops`
- `matrix`
- `ocr-numbers`
- `pascals-triangle`
- `pig-latin`
- `queen-attack`
- `rna-transcription`
- `robot-name`
- `robot-simulator`
- `rotational-cipher`
- `saddle-points`
- `scrabble-score`
- `secret-handshake`
- `simple-cipher`
- `space-age`
- `tree-building`
- `triangle`
- `word-count`
- `wordy`

**Comment by mcmillhj** [comment]
We also have `flatten-array` and `difference-of-squares` currently.
