### ISSUE TITLE
python dependencies unclear

### ISSUE THREAD

**Issue by dwschrashun** [exercism/sml#78]
When attempting to generate new README.md and test.sml files, running into errors with missing python libraries. It is unclear to me based on current documentation what python libraries / versions are necessary to successfully run the bin/generate command for an exercise.

library error examples:
- missing pathlib module
- missing request module

**Comment by snahor** [comment]
Oh, my bad, forgot to add that info. Please check #79.

**Comment by dwschrashun** [comment]
Great, thanks!
