### ISSUE TITLE
Launch planning

### ISSUE THREAD

**Issue by kytrinyx** [exercism/sml#8]
_Note: the launch checklist was woefully outdated, since this got created over two years ago, so I deleted it._

We have a launch guide that we'll keep up to date with changes here: https://github.com/exercism/docs/blob/master/language-tracks/launch/README.md

**Comment by kytrinyx** [comment]
@snahor @mcmillhj I can't see that I've invited you to maintain the track—which is a travesty. You should both have commit on this! Let me know if it's OK to add you.

**Comment by kytrinyx** [comment]
Oh. Hah. I seem to have discovered this last week as well: https://github.com/exercism/xsml/pull/36 My brain is having trouble containing all the things.

**Comment by snahor** [comment]
Hey @kytrinyx good to hear from you! Sure, add me, I'll be more than happy to help.

**Comment by kytrinyx** [comment]
Fantastic! I've invited you both. I'm going to take a look at the existing PRs to see if I can help clean up a bit.

**Comment by kytrinyx** [comment]
(that was quick) - it looks like you've got this under control. Let me know if I can help resolve conflicts or anything.

**Comment by kytrinyx** [comment]
I've updated this issue to contain a link to the new launch guide.

**Comment by sshine** [comment]
Since this language track is no longer new, I am closing this issue.

Issues related to renewing the track to v2 or v3 will be handled elsewhere.
