### ISSUE TITLE
Update exercises: test.sml

### ISSUE THREAD

**Issue by snahor** [exercism/sml#80]
The following exercises need to be updated:

- [x] accumulate
- [x] allergies
- [x] anagram
- [x] flatten-array
- [x] hamming
- [x] nth-prime
- [x] raindrops

Instructions:

To generate `test.sml`
```
$ bin/generate {exercise}
```

**Notes:** 
- The generator will overwrite `testlib.sml`, `test.sml`, `example.sml` and `{exercise}.sml`.
- Update`example.sml` and `{exercise}.sml` if needed.

**Comment by hanjiexi** [comment]
I attempted to run:
```bash
bin/generate flatten-array
```
But this produced:
```python
`[flatten-array]: ('Failed to infer a proper type, got multiple types', [1, [2, 3, 4, 5, 6, 7], 8], {'int', 'int list'})
```
My sml and problem-specifications repos are both fully up to date, so I'm not sure what's going on. I see that this error message came from line 61 of bin/generate, inside the `sml_type` function.

**Comment by mcmillhj** [comment]
The generator likely won't work 100% of the time due to type mismatches or the canonical-data.json file not existing. In these cases the files will have to be created manually.

**Comment by mcmillhj** [comment]
You could leave that one to us if you are unsure how to proceed, or you can push a PR for it and we can give feedback. Feel free to let me know if you have specific questions.

**Comment by hanjiexi** [comment]
Thanks for the clarification, for now I'll leave that one to you. But if I change my mind I'll post here again to let people know that it's being worked on.

**Comment by snahor** [comment]
@hanjiexi I've updated the generator https://github.com/exercism/sml#generator, it could help you the next time.
